# Generated by Django 4.2.24 on 2026-03-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("card", "Card"), ("transfer", "Transfer")],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="total_profit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_profit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total Profit"
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="profit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Product Image",
            ),
        ),
    ]
