# Generated by Django 4.2.24 on 2026-03-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_company_payment_method_company_total_profit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Is Deleted"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="Is Draft"),
        ),
        migrations.CreateModel(
            name="InvoiceAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.invoice",
                    ),
                ),
            ],
        ),
    ]
