# Generated by Django 4.2.29 on 2026-03-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="total_profit",
        ),
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Is Available"),
        ),
    ]
