# Generated by Django 4.2.24 on 2026-03-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auditlog_remove_invoice_is_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Cost Price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Selling Price",
            ),
        ),
    ]
