# Generated by Django 4.2.24 on 2026-04-26 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_product_cost_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Supplier"
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("company", "Company Expense"),
                            ("personal", "Personal Expense"),
                        ],
                        default="company",
                        max_length=20,
                        verbose_name="Expense Type",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Amount",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Created By"
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Purchase",
                "verbose_name_plural": "Internal Purchases",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Stock Quantity"),
        ),
        migrations.CreateModel(
            name="InternalPurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Cost"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.internalpurchase",
                    ),
                ),
            ],
        ),
    ]
