# Generated by Django 4.2.24 on 2026-04-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_internalpurchase_product_stock_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalpurchase",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("unpaid", "Unpaid"),
                ],
                default="unpaid",
                max_length=10,
                verbose_name="Payment Status",
            ),
        ),
        migrations.AddField(
            model_name="internalpurchase",
            name="total_paid",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total Paid"
            ),
        ),
    ]
