# Generated by Django 4.2.24 on 2026-04-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_internalpurchase_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalpurchase",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="internalpurchase",
            name="expense_type",
            field=models.CharField(
                choices=[
                    ("company", "Company Expense"),
                    ("personal", "Personal Expense"),
                ],
                db_index=True,
                default="company",
                max_length=20,
                verbose_name="Expense Type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Product Name"
            ),
        ),
    ]
