# Generated by Django 4.2.29 on 2026-05-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_internalpurchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='density',
        ),
        migrations.AddField(
            model_name='invoice',
            name='sell_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('bulk_wholesale', 'Bulk Wholesale')], default='retail', max_length=20, verbose_name='Sell Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bulk Wholesale Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Wholesale Price'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Density',
        ),
    ]
